# Part 1. Python Basics

This is a brief overview of Python language. It is aimed at students having at least one semester of programming experience in some language, such as Java, C, or Matlab. Our goal is not to become experts in programming in Python, but to learn enough so we can quickly become functional in doing data science with Python. 

**Disclaimer**: This file is a modification of several sources including:

- `cs228-python-tutorial.ipynb` at https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb from Stanford's CS228 course
(http://cs109.github.io/2015/)
- `appendix_python.ipynb` at http://nbviewer.jupyter.org/github/pydata/pydata-book/blob/master/appendix_python.ipynb, which is acompanying a very nice book "Python for Data Analysis" book by Wes McKinney.
- `Lab1-babypython.ipynb` at https://github.com/cs109/2015lab1 from Harvard's CS109 Data Science course 
- Python documentation at https://docs.python.org/2/index.html.
- CIS3715 Dat

## Installing Python IDE

**Python environments**. In this course we will encourage students to do their Python work using either *Spyder* or *iPython notebook*. 

Spyder is an interactive development environment (IDE) which has Graphical User Interface (GUI) very similar to Matlab, so it will immediatelly come naturally to anybody who previously used Matlab. But, even for those who have never heard of Matlab, Spyder provides a very pleasant environment to work with. It has several tiled windows where programmers can see the console to run their code, python (`.py`) file editor, as well as view variables and files. 

iPython notebook (often called Jupyter) is a web-based IDE which is run on a browser and allows programmers to write and run their code within a browser window and to also create html-like documents (`.ipynb`) that are a mix of code and nicely formatted comments.

**Anaconda**. We recommend students to start by installing `Anaconda` software on their own laptops or PCs (there are versions for Windows, OSX, and Linux) and use that software to start either Spyder or iPython notebook. *Anaconda* software can be downloaded for free from https://www.continuum.io/downloads. We advise installing Python 3 version for the purposes of this course. To install the software requires about 2GB of free disk space. Upon starting *Anaconda*, a window will pop up with several large icons. Clicking the *Launch* button on the *jupyter notebook* icon will launch iPython notebook. Clicking *Launch* button on the *spyder* icon will launch Spyder.

**Spyder** (reference: http://pythonhosted.org/spyder/). Let us launch Spyder. We recommend using *iPython console*. In the *iPython console* window, type `?` and press enter. You will see a quick introduction and overview of IPython's features. Try to red through it. Next, type `1+1` and press enter. As the result you should see the output `2`. That is it for now. 

**iPython Notebook** (reference: https://ipython.org/ipython-doc/3/notebook/notebook.html). Let us launch the *jupyter notebook*. You will see a list of files and folders visible from your root directory. Open file `CIS3715 (Temple - Spring 2020) PythonBasics.ipynb` from the folder where you saved it. Now, you will be able to see a version of this file that you can edit and run pieces of code from. You are advised to make a copy of this file (click *File->Make a Copy*) that you will edit and you can always switch back to the original file if needed.

## Python tutorial - baby steps
Let us start by running some basic code in python. If you click on the window below and press *Shift-Enter*, you will execute the code. You might also wish to copy-paste the chunks of code below to a *Spyder* console and execute them there.

In [118]:
1+2

3

Feel free to click on the code above and change the entry into `1+2` and press *Shift-Enter*.

You can also double click on the text you are looking at (it is in the *Markdown* format) and you will be able to modify it. After editing, remember to press *Shift-Enter*, so the changes will be implemented. You can find a nice intro about the *Markdown* on http://daringfireball.net/projects/markdown/

The following piece of code creates and assigns a value to object `b`, prints the value, and shows the type of the object. 

In [119]:
b = -2.5
print (b)
print (type(b))

-2.5
<class 'float'>


`print` is among a small number of Python keywords and `type()` is among a small number of built-in functions coming with any Python interpreter. For the full list of the keywords see https://learnpythonthehardway.org/book/ex37.html
and for the full list of built-in functions see https://docs.python.org/2/library/functions.html. 

Each object typically has associated a set of *attributes*, which are other objects stored in it, and *methods*, which define allowable things that could be done with the object. Now that we have created object `b`, which happens to be of type `float`, we can be wondering what could be done with it. To check properties of objects of type `float` we can type

In [120]:
help("float")

Help on class float in module builtins:

class float(object)
 |  float(x=0, /)
 |
 |  Convert a string or number to a floating-point number, if possible.
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __ceil__(self, /)
 |      Return the ceiling as an Integral.
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floor__(self, /)
 |      Return the floor as an Integral.
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self

From this listing, we can see the allowable methods that could be applied on any object of `float` type to which `b` belongs. For example, to find an absolute value of `b` we can type 

In [121]:
print (b.__abs__())   # this is a cumbersome way to find the absolute value
print (abs(b))   # this is the standard way 

2.5
2.5


Another way to see the attribtes and methods for `b` is to type `dir("float")` or directly `dir(b)`. You can also use `?` to get more information, such as by typing `b?` . While entering code in *iPython notebook* or *Spyder* , it is also useful to use autocompletion, which is envoked by pressing the *Tab* button. Try to press *Tab* in the window below and select `is_integer` choice. 

In [122]:
import IPython; print(IPython.__version__)

8.32.0


In [123]:
b?

Type:        float
String form: -2.5
Docstring:   Convert a string or number to a floating-point number, if possible.

Since `is_integer` is a method, we can execute it by adding parentheses

In [124]:
b.is_integer()

False

# Typing
In addition to `float` Python has several important built-in types that are worth knowing. One group are *simple types* that allow handling of numerical data, strings, boolean values, dates, and time. Another group are *container types* that contain numerous objects of simple type. 

##   Simple Types

**Numbers**. Integers and floats work as you would expect from other languages:

In [125]:
c = 3
print (c, type(c))

3 <class 'int'>


In [126]:
print (c + 1)   # Addition (by the way, any text following '#' is treated as a comment)
print (c * 2)   # Multiplication
print (c / 2)   # Division (pay attention that the result is the integer part, not float 1.5)
print (c ** 2)  # Exponentiation

4
6
1.5
9


In [127]:
c += 1
print (c)  # Prints "4"
c *= 2
print (c)  # Prints "8"

4
8


Operations between `float` and `integer` types are possible and the result is typed as `float`

In [128]:
print (b+c, type(b+c))

5.5 <class 'float'>


It is also possible to convert one type into another by using the built-in functions `float` and `int`

In [129]:
b = int(b)
print (b, type(b))
c = float(c)
print (c, type(c))

-2 <class 'int'>
8.0 <class 'float'>


With those type conversions, Python had to delete the existing object and create a new object with different type. Note that upon using the assign operator, Python is trying to guess the type of the object. If upon checking the type, the programmer does not agree, (s)he might want to change the type, as shown above. Python also has built-in types for long integers and complex numbers; you can find all of the details at https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex.

**None**. Another important simple type is *None* and is used quite often in data science:

In [130]:
n = None
print (n, type(n))

None <class 'NoneType'>



**Booleans**. Python implements all of the usual operators for Boolean logic, either by using English words (e.g., `and`, `or`, `not` -- preferred for readability) or symbols (e.g., `&`, `|`):

In [131]:
t = True
f = False
print (t, type(t), f, type(f))  

True <class 'bool'> False <class 'bool'>


In [132]:
print (t and f) # Logical AND;
print (t or f)  # Logical OR;
print (not t)   # Logical NOT;
print (t != f)  # Logical XOR;

False
True
False
True


**Strings**. `str` is a very useful type. It is defined by assigning a *string literal* enclosed with single or double quotes

In [133]:
s1 = 'hello'       # string literals can use single quotes
print (s1, len(s1), type(s1))    # len() is a method that works on strings, check len? or help("len")
s2 = "hello"       # string literals can also be defined using double quotes
print (s2)
s3 = '''           
longer text
  that can span
 multiple lines
'''
print (s3)           # triple quote is used for multi-line string literals
s1 == s2           # this will output True because the objects have the same content

hello 5 <class 'str'>
hello
           
longer text
  that can span
 multiple lines



True

In [134]:
s4 = s1 + ' is the same as ' + s2     # string concatenation
print (s4)
s5 = '%s %s %d' % (s1, 'world', 12)  # sprintf style string formatting
print (s5)  # prints "hello world 12"

hello is the same as hello
hello world 12


String objects have many useful methods (see https://docs.python.org/2/library/stdtypes.html#string-methods for more details)

In [135]:
s = "hello"
print (s.capitalize())  # Capitalize a string; prints "Hello"
print (s.upper())       # Convert a string to uppercase; prints "HELLO"
print (s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print (s.center(7))     # Center a string, padding with spaces; prints " hello "
print (s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print ('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


## Container Types
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

**Lists** (reference https://docs.python.org/2/tutorial/datastructures.html#more-on-lists). A list is the Python equivalent of an array, but is resizeable and can contain elements of different types. It is created by using square brackets.

In [136]:
xs = [3, 1, 2]   # Create a list
print (xs)

[3, 1, 2]


Each element of the list can be accessed using the bracket notation. Each element can be changed. The elements of the list do not have to be of the same type. Elements can be added or deleted using the appropriate methods.

In [137]:
print (xs[0])             # the first element of a list has index 0
xs[1] = 'hello again'   # changing the second element from integer to string type
print (xs)
print (type(xs), type(xs[0]), type(xs[1]))
xs.append(99.99)     # add a new element at the end of the list
print (xs)
x = xs.pop(2)        # remove the third element and return its value
print (x, xs)

3
[3, 'hello again', 2]
<class 'list'> <class 'int'> <class 'str'>
[3, 'hello again', 2, 99.99]
2 [3, 'hello again', 99.99]


Lists can contain lists as elements

In [138]:
xbig = [xs, 1, 'hello']
print (xbig)

[[3, 'hello again', 99.99], 1, 'hello']


In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing.

In [139]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print (nums)         # Prints "[0, 1, 2, 3, 4]"
print (nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print (nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print (nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print (nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print (nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [88, 99] # Assign a new sublist to a slice
print (nums)         # Prints "[0, 1, 88, 99, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 88, 99, 4]


**Tuples** (reference: https://docs.python.org/2/tutorial/datastructures.html#tuples-and-sequences). A tuple is an (immutable) ordered list of values. It is defined using parentheses.

In [146]:
t = (5, 6)       # Create a tuple
print (t, type(t))

(5, 6) <class 'tuple'>


A tuple is in many ways similar to a list. One of the most important differences is that tuples can be used as keys in dictionaries (defined next) and as elements of sets, while lists cannot

In [141]:
dict2 = {(x, x + 1): x for x in range(6)}  # Create a dictionary with tuple keys (do not worry about the logic for now)
print (dict2)
print (dict2[t])       
print (dict2[(1, 2)])

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5}
5
1


In [147]:
t[0] = 1         # tuples are immutable

TypeError: 'tuple' object does not support item assignment

**Dictionaries** (reference: https://docs.python.org/2/library/stdtypes.html#dict). A dictionary stores (key, value) pairs called *items*, similar to a Map in Java or an object in Javascript. It is created using the curly braces.

In [25]:
dct = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print (dct, type(dct))
print (dct['cat'])       # Get an entry from a dictionary; prints "cute"
print (dct.keys())       # prints a list of all the keys
print (dct.values())     # prints a list of all the values
print (dct.items())      # prints a list of all (key,value) tuples
print ('cat' in dct)     # Check if a dictionary has a given key; prints "True"

{'cat': 'cute', 'dog': 'furry'} <class 'dict'>
cute
dict_keys(['cat', 'dog'])
dict_values(['cute', 'furry'])
dict_items([('cat', 'cute'), ('dog', 'furry')])
True


It is relatively straightforward to add new entries, modify the existing entries, or delete the existing entries

In [26]:
dct['fish'] = 'wet'      # Set an entry in a dictionary
print (dct['fish'])        # Prints value of key 'fish'
dct['dog'] = 'friendly'  # Change the value of key 'dog'
print (dct)
del dct['cat']          # Remove an element from a dictionary
print (dct) 
dct[12] = 8             # keys and values in a dictionary can be of different types
print (dct)

wet
{'cat': 'cute', 'fish': 'wet', 'dog': 'friendly'}
{'fish': 'wet', 'dog': 'friendly'}
{'fish': 'wet', 12: 8, 'dog': 'friendly'}


Sometimes, we may wish to obtain a value for a specific key, but do not know if the element exists. Making the following creates an error message

In [27]:
print (dct['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: 'monkey'

To prevent the error, the `get` method should be used (enter `help("dict")` to learn about all the methods for `dict` type)

In [28]:
print (dct.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print (dct.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

N/A
wet


Dictionaries are very interesting from the data structures perspective -- they are related to the idea of hash tables.

**Sets** (reference: https://docs.python.org/2/tutorial/datastructures.html#sets). A set is an unordered collection of distinct elements. It is defined using curly braces.

In [29]:
animals = {'cat', 'dog'}
print (animals, type(animals))
print ('cat' in animals)   # Check if an element is in a set; prints "True"
print ('fish' in animals)  # prints "False"
animals.add('cat')       # Adding an element that is already in the set does nothing
print (animals)       
animals.remove('cat')    # Remove an element from a set
print (animals)      

{'cat', 'dog'} <class 'set'>
True
False
{'cat', 'dog'}
{'dog'}


# Control flow of Python
Similarly to other languages, Python allows control flow through conditionals (e.g., if-else) and loops (e.g., for loops, while loops).

## if-elif-else

In [30]:
b = 2
if b < 0:
    print ("It's negative")
elif b == 0:
    print ('Equal to zero')
elif 0 < b < 5:
    print ('Positive but smaller than 5')
else:
    print ('Positive and larger than 5')

Positive but smaller than 5


As you can see, the main difference is in syntax. if-elif-else does not require parentheses. Instead, text indentation is used to identify blocks of code. Luckily, both *iPython notebook* and *Spyder* editors are helpful in avoiding syntax errors with the indentation.

## While loops

In [31]:
x = 256
total = 0
while x > 0:
    if total > 500:
        break        # leaves the loop
    total += x
    x = x // 2
    print (x, total)
print ('finally, the values are: ', x, total)

128 256
64 384
32 448
16 480
8 496
4 504
finally, the values are:  4 504


## For loops

`for` loops are somewhat different than in Java, C, or Matlab. Rather than giving the user the ability to define both the iteration step and halting condition (as C), Python’s for statement iterates over the items of any sequence (e.g., list, string, dictionary), in the order that they appear in the sequence. You will learn to like for loops once you get used to them.

In [32]:
sum = 0
for i in range(5):  # range(5) creates a list [0, 1, 2, 3, 4], 'i' are iterated through the values in this list 
    sum += i
print (sum)           # reports the sum of the elements in the list

10


Here is another example that iterates through the elements of a provided list.

In [33]:
sequence = [1, 2, None, 4, None, 5]
total = 0
for value in sequence:
    if value is None:      # what does keyword 'is' do?
        continue           # skip the rest of the block, keep looping
    total += value
print (total)

12


`for` loops can also be iterated over dictionary items 

In [34]:
dct = {'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}  # Create a new dictionary with some data
for key in dct:                    # iterates over keys of a dictionary
    print (key)
for key,value in dct.items():      # items method returns a list of (key,value) pairs
    print (key, 'is', value)

cat
fish
dog
cat is cute
fish is wet
dog is furry


The role of keword `in` might be confusing. If you are really curious about it, the following Stack Overflow post might be helpful http://stackoverflow.com/questions/38204342/python-in-keyword-in-expression-vs-in-for-loop.

# Scripts, Modules and Packages
**Scripts**. If you quit from the Python interpreter and restart it, all the code you have run, including the definitions, are lost. To reuse the code, it is a good idea to use a text editor to save the reusable code. A typical extension for the saved file would be `.py`. In *Spyder*, you can paste any code from the above in a `.py` file, let us say `test.py`, save in the current directory and type `execfile("test.py")` in the console. This is known as creating and running a *script*. You can also run your script by pressing the *Play* icon in the menu.

**Modules and Packages**. Any Python file with the `.py` extension is a module. If the file contains useful definitions that you would like to use, there is a simple mechanism to *import* it. Python comes with a library of standard modules, described in https://docs.python.org/2/library/datetime.html. A package is a collection of Python modules. While a module is a single Python file, a package is a directory of Python modules. Anaconda software comes with a list of packages (see https://docs.continuum.io/anaconda/pkg-docs) that could be imported in the same way as standard library modules.

In [ ]:
import datetime                 # this is a standard Python module
print (datetime.date(2017,1,17))  # uses method data from module datetime to create a date object and prints its value
import numpy                    # this is a very popular package in the Anaconda release
print (numpy.random.rand(4,3), '\n')    # prints out a 4x3 array of random numbers
import numpy as np              # provides an alias for numpy, allows shorter codes
print (np.random.rand(4,3), '\n')       # also prints out a 4x3 array of random numbers
from numpy.random import rand   # allows us to directly call numpy.random.rand function as rand
print (rand(4,3))                 # also prints out a 4x3 array of random numbers

2017-01-17
[[0.71161756 0.05987998 0.99136672]
 [0.5319522  0.87154702 0.27000679]
 [0.82097328 0.94226006 0.65085838]
 [0.63161473 0.42534873 0.36819438]] 

[[0.35785191 0.08803317 0.01137334]
 [0.55350542 0.39474059 0.1311278 ]
 [0.30096158 0.79870163 0.13506683]
 [0.39383783 0.33210435 0.17473325]] 

[[0.30539664 0.62616752 0.21248388]
 [0.16083718 0.90392722 0.55300611]
 [0.49715595 0.52906077 0.39594704]
 [0.42528073 0.53374456 0.3235156 ]]


# Navigating the Python universe
This tutorial provides just a glimpse at Python. For experienced programmers, Library reference and Language reference in https://docs.python.org/2.7/index.html describe almost all we need to know about Python and its standard modules, but those documents are a bit dense for beginners. It would probably take too much time for a typical student to learn Python by going through those references. Moreover, those references do not contain any information about non-standard library packages developed by a large number of volunteers around the world. The appeal and power of Python lies largely in those packagesFor example, some of those packages, such as `numpy`, `scipy`, `pandas`, `matplotlib`, `scikit-learn` have become the standard tools of a modern data scientist. The question is how to proceed with learning Python and many of its important packages?  

Probably the best advice is to learn Python by doing it and by using online and printed resources. 
- **online tutorials**, many of them available as `ipynb` files, such as the ones used to create this document
- **online reference materials** provided with packages: Scipy and Numpy (https://docs.scipy.org/doc/), Pandas (http://pandas.pydata.org/pandas-docs/stable/index.html), Matplotlib (http://matplotlib.org/), Scikit-learn (http://scikit-learn.org/stable/)
- **google search**: many, if not most, of the programming-related questions queried with Google have an answer and often lead to the Stack Overflow, which has a huge repository of all kinds of questions related to programming, including programming in Python. Querying of Stack Overflow using Google search is so successful, that some computer scientists are jokingly saying that programming is an art of copying code from Stack Overflow. Of course, Google search has a much wider reach and allows us to access extremely valuable resources. Just to whet the appetite, let us enter "python for data analysis ipynb" and observe some great resources and tutorials for data scientists.
- **books** such as "python for data scientists". This particular book comes with an online appendix with all the code used in the book (https://github.com/wesm/pydata-book). Some books come available in both print and electronic formats.

In the context of CIS3715 course, you should feel free to browse internet and copy or modify the existing code, as long as you acknowledge your source. It is also completely OK to talk to your class colleagues. However, in this case, in addition to acknowledging any help, please be careful to refrain from copying homework and lab solutions from your colleagues. In case of doubt, please consult your instructors.

## Task: 

- Study the attached [slides](./LabAssignment1.pdf) and try all the codes in this slides. 

- Submit your code (jupyter notebook) via Canvas.

## 1. Example

### 1.1 Load data with pandas

In [40]:
# this is your code to get two vectors
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print()
print(X.shape)
print()
print(X)

<class 'numpy.ndarray'>

(406, 7)

[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


### 1.2 Operation for vector

In [10]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print()
print(x2)
print()

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]

[28.0 4 120.0 79 2625 18.6 82]

[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [7]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print()
print(m2)
print()

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]

[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]

[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X


In [18]:
# this is your code to get two vectors

y1 = X[:,0]
y2 = X[:,-2]

print(y1)
print()
print("hello")
print(y2)

[18.0 15.0 18.0 16.0 17.0 15.0 14.0 14.0 14.0 15.0 0.0 0.0 0.0 0.0 0.0
 15.0 14.0 0.0 15.0 14.0 24.0 22.0 18.0 21.0 27.0 26.0 25.0 24.0 25.0 26.0
 21.0 10.0 10.0 11.0 9.0 27.0 28.0 25.0 25.0 0.0 19.0 16.0 17.0 19.0 18.0
 14.0 14.0 14.0 14.0 12.0 13.0 13.0 18.0 22.0 19.0 18.0 23.0 28.0 30.0
 30.0 31.0 35.0 27.0 26.0 24.0 25.0 23.0 20.0 21.0 13.0 14.0 15.0 14.0
 17.0 11.0 13.0 12.0 13.0 19.0 15.0 13.0 13.0 14.0 18.0 22.0 21.0 26.0
 22.0 28.0 23.0 28.0 27.0 13.0 14.0 13.0 14.0 15.0 12.0 13.0 13.0 14.0
 13.0 12.0 13.0 18.0 16.0 18.0 18.0 23.0 26.0 11.0 12.0 13.0 12.0 18.0
 20.0 21.0 22.0 18.0 19.0 21.0 26.0 15.0 16.0 29.0 24.0 20.0 19.0 15.0
 24.0 20.0 11.0 20.0 21.0 19.0 15.0 31.0 26.0 32.0 25.0 16.0 16.0 18.0
 16.0 13.0 14.0 14.0 14.0 29.0 26.0 26.0 31.0 32.0 28.0 24.0 26.0 24.0
 26.0 31.0 19.0 18.0 15.0 15.0 16.0 15.0 16.0 14.0 17.0 16.0 15.0 18.0
 21.0 20.0 13.0 29.0 23.0 20.0 23.0 24.0 25.0 24.0 18.0 29.0 19.0 23.0
 23.0 22.0 25.0 33.0 28.0 25.0 25.0 26.0 27.0 17.5 16.0 15.5 14.5 22.0

### 2.2 Perform following operations on these two vectors and print the result

In [21]:
# 1. addition and subtraction
print(y1+y2)
print()

# 2. element-wise multiplication
print(y1*y2)
print()

# 3. inner product
np.dot(y1, y2)
print()

# 4. three norms
print("y1 L1 norm = {}\n".format(np.linalg.norm(y1, ord=1)))
print("y1 L2 norm = {}\n".format(np.linalg.norm(y1)))
print("y1 Infinity norm = {}\n".format(np.linalg.norm(y1, np.inf)))
print("y2 L1 norm = {}\n".format(np.linalg.norm(y2, ord=1)))
print("y2 L2 norm = {}\n".format(np.linalg.norm(y2)))
print("y2 Infinity norm = {}\n".format(np.linalg.norm(y2, np.inf)))

# 5. compute the distance between these two vectors
print("distance = {}\n".format(np.linalg.norm(y1-y2)))

[30.0 26.5 29.0 28.0 27.5 25.0 23.0 22.5 24.0 23.5 17.5 11.5 11.0 10.5
 11.0 25.0 22.0 8.0 24.5 24.0 39.0 37.5 33.5 37.0 41.5 46.5 42.5 38.5 42.5
 38.5 36.0 24.0 25.0 24.5 27.5 41.5 43.5 39.0 44.0 20.0 32.0 31.5 32.5
 34.5 33.5 26.0 25.5 27.5 27.0 23.5 25.0 25.0 31.5 41.0 34.0 32.5 37.0
 42.0 49.5 44.5 50.0 53.0 46.0 46.5 39.5 42.0 46.5 39.5 37.5 25.0 26.0
 28.5 27.0 28.5 22.0 26.5 25.5 25.5 32.5 27.5 27.0 29.0 28.0 32.5 40.0
 40.5 44.0 38.0 45.0 37.5 43.0 43.5 26.0 25.5 26.0 28.5 27.5 23.5 25.0
 26.0 28.5 24.0 23.0 24.0 34.5 34.0 34.0 34.5 39.0 47.0 25.0 24.5 26.0
 24.5 33.0 39.0 40.5 38.5 31.5 37.5 35.0 41.5 28.0 25.5 48.5 39.5 34.0
 34.5 26.0 38.0 33.5 22.0 36.5 38.0 35.0 32.0 50.0 42.5 53.0 42.0 33.0
 34.0 34.5 30.0 27.5 27.5 30.0 29.5 45.5 41.5 40.5 47.5 51.0 42.5 39.5
 40.0 39.0 41.5 47.0 35.0 34.0 36.0 34.5 27.5 29.0 30.5 27.5 38.0 34.5
 34.0 37.0 36.0 33.5 25.0 45.0 40.0 36.0 41.5 37.5 41.5 41.0 32.5 43.0
 36.0 38.0 40.0 36.5 38.5 50.5 43.5 41.9 39.9 43.7 42.3 30.5 29.0 29.4
 2

### 2.3 Get the first three columns and the last three columns from X

In [91]:
# this is your code to get two matrices: A, B
A = X[:,0:3]
B = X[:,-3:]

print("{}\n".format(A))
print("{}\n".format(B))

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]
 ...
 [32.0 4 135.0]
 [28.0 4 120.0]
 [31.0 4 119.0]]

[[3504 12.0 70]
 [3693 11.5 70]
 [3436 11.0 70]
 ...
 [2295 11.6 82]
 [2625 18.6 82]
 [2720 19.4 82]]



### 2.4 Perform following operations on these two matrices and print the result

In [ ]:
# 1. addition and subtraction 
print("{}\n".format(A+B))
print("{}\n".format(A-B))

# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
C = B.T
print("{}\n".format(C.shape))

# 3. compute the product between A and C, and print the result and its shape
AC = np.dot(A,C)
print("{}\n".format(AC))
print("{}\n".format(AC.shape))

# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D = A.T
print("{}\n".format(D))

# 5. compute the product between D and B, and print the result and its shape
DB = np.dot(D,B)
print("{}\n".format(DB))
print("{}\n".format(DB.shape))

[[3522.0 20.0 377.0]
 [3708.0 19.5 420.0]
 [3454.0 19.0 388.0]
 ...
 [2327.0 15.6 217.0]
 [2653.0 22.6 202.0]
 [2751.0 23.4 201.0]]

[[-3486.0 -4.0 237.0]
 [-3678.0 -3.5 280.0]
 [-3418.0 -3.0 248.0]
 ...
 [-2263.0 -7.6 53.0]
 [-2597.0 -14.600000000000001 38.0]
 [-2689.0 -15.399999999999999 37.0]]

(3, 406)

[[84658.0 88056.0 83426.0 ... 66576.8 72572.8 74289.2]
 [77156.0 79987.0 76128.0 ... 63217.8 68223.8 69655.2]
 [85428.0 88826.0 84196.0 ... 67478.8 73474.8 75191.2]
 ...
 [121626.0 127672.0 119446.0 ... 84556.4 95144.4 98187.6]
 [106560.0 111850.0 104652.0 ... 74146.4 83414.4 86077.6]
 [117002.0 122859.0 114890.0 ... 80949.4 91207.4 94155.6]]

(406, 406)

[[18.0 15.0 18.0 ... 32.0 28.0 31.0]
 [8 8 8 ... 4 4 4]
 [307.0 350.0 318.0 ... 135.0 120.0 119.0]]

[[25614040.900000002 149295.04000000004 718009.0999999995]
 [7149030 33484.69999999997 167835]
 [269175402.0 1160836.2999999998 5943079.0]]

(3, 3)



## Python Basics Slides

### List

In [7]:
list1 = ["apple", "banana", "cherry"]
list2 = [1,5,7,9,3]
list3 = [True, False, False]

print(list1)
print(list2)
print(list3)

['apple', 'banana', 'cherry']
[1, 5, 7, 9, 3]
[True, False, False]


In [33]:
print(list1[0])
print(list1[-1])
print(list1[-2])

apple
cherry
banana


In [59]:
list4 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(list4[2:5])
print(list4[2:-2])

['cherry', 'orange', 'kiwi']
['cherry', 'orange', 'kiwi']


In [60]:
print(list1)
list1.append("orange")
print(list1)

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'orange']


In [61]:
print(list1)
list1.insert(1,"mango")
print(list1)

['apple', 'banana', 'cherry', 'orange']
['apple', 'mango', 'banana', 'cherry', 'orange']


In [62]:
tropical = ["pineapple", "papaya", "plantain"]
list1.extend(tropical)
print(list1)

['apple', 'mango', 'banana', 'cherry', 'orange', 'pineapple', 'papaya', 'plantain']


In [63]:
list1.remove("banana")
print(list1)

['apple', 'mango', 'cherry', 'orange', 'pineapple', 'papaya', 'plantain']


In [65]:
for x in list1:
    print(x)
print()
for i in range(len(list1)):
    print(list1[i])

apple
mango
cherry
orange
pineapple
papaya
plantain

apple
mango
cherry
orange
pineapple
papaya
plantain


### Tuples

In [66]:
thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)

('apple', 'banana', 'cherry', 'apple', 'cherry')


In [67]:
print(thistuple[1])
print(thistuple[-2])
print(thistuple[2:5])

banana
apple
('cherry', 'apple', 'cherry')


In [68]:
fruits = ("apple", "banana", "cherry")
(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
cherry


In [69]:
for x in thistuple:
    print(x)
print()
for i in range(len(thistuple)):
    print(thistuple[i])

apple
banana
cherry
apple
cherry

apple
banana
cherry
apple
cherry


## Dictionaries

In [144]:
thisdict = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}
print(thisdict)
print(thisdict["brand"])

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Ford


In [145]:
print(thisdict.keys())
print(thisdict.values())
print(thisdict.items())

dict_keys(['brand', 'model', 'year'])
dict_values(['Ford', 'Mustang', 1964])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])


In [150]:
thisdict["color"] = "blue"
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'blue'}


In [151]:
thisdict.update({"year":"2021"})
print(thisdict)
thisdict.update({"color":"red"})
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': '2021', 'color': 'blue'}
{'brand': 'Ford', 'model': 'Mustang', 'year': '2021', 'color': 'red'}


In [152]:
thisdict.pop("model")
print(thisdict)

{'brand': 'Ford', 'year': '2021', 'color': 'red'}


In [154]:
print("===keys===")
for x in thisdict.keys():
    print(x)
print("\n===values===")
for x in thisdict.values():
    print(x)
print("\n===items===")
for x in thisdict.items():
    print(x)


===keys===
brand
year
color

===values===
Ford
2021
red

===items===
('brand', 'Ford')
('year', '2021')
('color', 'red')
